vich_uploader:
    db_driver: orm
    storage: file_system
    mappings:
        candidate_photo:
            uri_prefix: /uploads/candidate/photos
            upload_destination: '%kernel.project_dir%/public/uploads/candidate/photos'
        candidate_cv:
            uri_prefix: /uploads/candidate/cv
            upload_destination: '%kernel.project_dir%/public/uploads/candidate/cv'
        company_logo:
            uri_prefix: /uploads/recruiter/logo
            upload_destination: '%kernel.project_dir%/public/uploads/recruiter/logo'
