vich_uploader:
    db_driver: orm
    storage: file_system
    mappings:
        candidate_photo:
            uri_prefix: /uploads/candidate/photo
            upload_destination: '%kernel.project_dir%/public/uploads/candidate/photo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # Example namer
        candidate_cv:
            uri_prefix: /uploads/cv
            upload_destination: '%kernel.project_dir%/public/uploads/cv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # Example namer
        company_logo:
            uri_prefix: /uploads/recruiter/logo
            upload_destination: '%kernel.project_dir%/public/uploads/recruiter/logo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # Example namer
